#! python3
# RevenueEmailAttachment.py - Search for specific email subject in Outlook, move the email 
# and download the attachment to specific location

from win32com.client import Dispatch
import datetime as date
import os.path

outlook = Dispatch("Outlook.Application").GetNamespace("MAPI")
inbox = outlook.GetDefaultFolder("6")
all_inbox = inbox.Items

# TODO: run for last two or three days?

val_date = date.date.today()

# TODO: add re to search for keyword

sub_today = 'Testing Python'
att_today = 'WHA Pick up 4 Mths_190103.xlsx'
for msg in all_inbox:
    if msg.Subject == sub_today:
    
    # TODO: Move the email to specific folder
    
        break

for att in msg.Attachments:
    if att.FileName == att_today:
        path = os.getcwd() + '\\new.xlsx'
        print(path)
        att.SaveAsFile(path)
        break


